# Generated by Django 5.0.7 on 2024-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="is_first_login",
        ),
        migrations.AddField(
            model_name="myuser",
            name="is_password_changed",
            field=models.BooleanField(default=False),
        ),
    ]
