# Generated by Django 5.0.7 on 2024-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_remove_myuser_is_first_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("user", "User"),
                ],
                default="user",
                max_length=30,
            ),
        ),
    ]
