version: '3'

services:
  backend:
    build: ./EITS_backend
    ports:
      - "8000:8000"
    volumes:
      - ./EITS_backend:/app
    depends_on:
      - db

  frontend:
    build: ./EITS_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./EITS_frontend:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: disSAMI!123
      MYSQL_DATABASE: electricinterruption
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
