# Generated by Django 5.0.7 on 2024-09-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="priorty",
            new_name="priority",
        ),
    ]
