# Generated by Django 5.1.3 on 2024-11-22 09:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Interruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_id', models.PositiveIntegerField()),
                ('related_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Interruption Type')),
            ],
        ),
        migrations.CreateModel(
            name='InterruptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('handled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interruption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electric_Line.interruption')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_interruptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('voltage_level', models.CharField(choices=[('LV', 'low level 100v-1kv'), ('MV', 'medium level  1kV to 36kV'), ('HV', 'high level 36kV to 230kV. '), ('EHV', 'Extra high level  230kV to 765kV'), ('UHV', 'Ultra high level > 765kV')], max_length=10)),
                ('height', models.FloatField(help_text='SI unit Metre')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electric_Line.location')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_account', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_partner', models.CharField(max_length=255)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='Electric_Line.pole')),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=55, unique=True)),
                ('created_at', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electric_Line.location')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=55, unique=True)),
                ('created_at', models.DateField()),
                ('type_of_CB', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electric_Line.location')),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switching_station', to='Electric_Line.substation')),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('voltage_level', models.CharField(max_length=255)),
                ('length', models.PositiveIntegerField(help_text='SI unit KM')),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('coverage_area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateField()),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_lines', to='Electric_Line.location')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_lines', to='Electric_Line.location')),
                ('switching_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeders', to='Electric_Line.switchingstation')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('rating', models.CharField(help_text='SI unit KVA', max_length=255)),
                ('cooling', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('manufacturing_date', models.DateField()),
                ('property_of', models.CharField(choices=[('EEU', 'Ethiopian,Electric Utility'), ("Customer's", "customer's property")], default='EEU', max_length=55)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformer', to='Electric_Line.feeder')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electric_Line.location')),
            ],
        ),
        migrations.AddField(
            model_name='pole',
            name='transformer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Electric_Line.transformer'),
        ),
    ]
