# Generated by Django 5.1.3 on 2024-11-15 17:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electric_Line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_account', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('business_partner', models.CharField(max_length=255)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='Electric_Line.pole')),
            ],
        ),
    ]
