# Generated by Django 5.1.3 on 2024-11-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Electric_Line', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeder',
            name='location',
        ),
    ]
