# Generated by Django 5.1.3 on 2024-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electric_Line', '0003_remove_feeder_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pole',
            name='total_user',
        ),
        migrations.AlterField(
            model_name='pole',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pole',
            name='height',
            field=models.FloatField(help_text='SI unit Metre'),
        ),
    ]
