# Generated by Django 5.0.7 on 2024-09-03 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeder", models.CharField(max_length=50)),
                ("express", models.CharField(max_length=50)),
                ("frequency", models.IntegerField()),
                ("duration", models.DurationField()),
                ("year", models.IntegerField(blank=True, null=True)),
                ("period", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterruptionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feeder",
                    models.CharField(
                        choices=[
                            ("R1", "R1"),
                            ("R2", "R2"),
                            ("R3", "R3"),
                            ("R4", "R4"),
                            ("R5", "R5"),
                            ("R6", "R6"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "express",
                    models.CharField(
                        choices=[
                            ("01", "01"),
                            ("02", "02"),
                            ("03", "03"),
                            ("04", "04"),
                            ("05", "05"),
                            ("06", "06"),
                            ("IN", "IN"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "G_express",
                    models.CharField(
                        choices=[
                            ("G1", "G1"),
                            ("G2", "G2"),
                            ("G3", "G3"),
                            ("G4", "G4"),
                            ("G5", "G5"),
                            ("G6", "G6"),
                            ("IN", "IN"),
                            ("Locally", "Locally"),
                            ("Manually", "Manually"),
                            ("G2/G1", "G2/G1"),
                            ("G3/G1", "G3/G1"),
                            ("G4/G1", "G4/G1"),
                            ("Substation", "Substation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Fault", "Fault"),
                            ("Operation", "Operation"),
                            ("Load", "Load"),
                            ("Over-Load", "Over-Load"),
                            ("Substation", "Substation"),
                            ("other", "other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("operator", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_upload",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
