# Generated by Django 5.0.7 on 2024-09-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interruption_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interruptiondata",
            name="express",
            field=models.CharField(
                choices=[
                    ("R1", "R1"),
                    ("R2", "R2"),
                    ("R3", "R3"),
                    ("R4", "R4"),
                    ("R5", "R5"),
                    ("R6", "R6"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interruptiondata",
            name="feeder",
            field=models.CharField(
                choices=[
                    ("01", "01"),
                    ("02", "02"),
                    ("03", "03"),
                    ("04", "04"),
                    ("05", "05"),
                    ("06", "06"),
                    ("IN", "IN"),
                ],
                max_length=50,
            ),
        ),
    ]
